# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='hero',
        ),
    ]
