# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_app', '0002_remove_power_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='heroes',
            field=models.ManyToManyField(related_name='powers', to='heroes_app.Hero'),
        ),
    ]
