# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('heroes_app', '0003_power_heroes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='user_likes',
            field=models.ManyToManyField(related_name='heroes_likes', to='login_app.User'),
        ),
    ]
